//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSDC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FSDCEntities : DbContext
    {
        public FSDCEntities()
            : base("name=FSDCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<staff_projects> staff_projects { get; set; }
    }
}
